# Écoute sur toutes les interfaces
listener 1883 0.0.0.0
protocol mqtt
# Autoriser les connexions sans mot de passe
allow_anonymous true
# Configuration pour les WebSockets
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true
# Logs pour debug
log_type all
